### ISSUE TITLE
易班更新了

### ISSUE THREAD

**Issue by ailbbi46** [supertsy5/fake-yiban#1]
易班更新了审批通过的图标（图标的五角星会顺时针旋转），我想问问需要怎么更改，是直接改里面的图片（如果改图片，那怎么建立新链接），还是说有其他方法

**Comment by supertsy5** [comment]
抱歉现在才回复。我检查了新版的图标，发现旋转的五角星是单独的另一张图片；需要改一些代码。

**Comment by supertsy5** [comment]
>

**Comment by supertsy5** [comment]
抱歉现在才回复。我检查了新版的图标，发现旋转的五角星是单独的另一张图片；需要改一些代码。
相关的文件已放到`/src/components/fake/stars.png, star_back.png`。稍后我会改代码。

**Comment by supertsy5** [comment]
已更新，请点击首页的`Start`查看

**Comment by supertsy5** [comment]
另外我希望能和你取得直接联系，我的邮箱是 supertsy5@proton.me
